<<<<<<< HEAD
;;; Automatically generated by ‘recentf’ on Wed Jul 12 20:23:39 2023.

(setq recentf-list
      '(
        "/home/kim/.config/awesome/awesome-wm-widgets/volume-widget/README.md"
=======
;;; Automatically generated by ‘recentf’ on Wed Jul 12 06:10:11 2023.

(setq recentf-list
      '(
        "/home/kim/.dots/.git/COMMIT_EDITMSG"
>>>>>>> 46bee93 (added widgets)
        "/home/kim/.dots/config/awesome/rc.lua"
        "/home/kim/.config/awesome/rc.lua"
        "/home/kim/.dots/.emacs.d/init.el"
        "/home/kim/.dots/.xinitrc"
        "/home/kim/.xinitrc"
        "/home/kim/.config/awesome/themes/default/theme.lua"
        "/home/kim/.dots/config/alacritty/alacritty.yml"
        "/home/kim/.emacs.d/init.el"
        "/home/kim/.config/alacritty/alacritty.yml"
        "/home/kim/.dots/.emacs.d/orgmode.el"
        "/home/kim/Dokumenter/mastering-emacs-v4.pdf"
        "/home/kim/.dots/.emacs.d/mail.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
