;;; Automatically generated by ‘recentf’ on Thu Jul  6 06:44:21 2023.

(setq recentf-list
      '(
        "/home/kim/org/org/opgaver.org"
        "/home/kim/org/opgaver.org"
        "/home/kim/org/på"
        "/home/kim/.dots/opgaver.org"
        "/home/kim/.dots/.emacs.d/orgmode.el"
        "/home/kim/.dots/.emacs.d/init.el"
        "/home/kim/.emacs.d/init.el"
        "/home/kim/Dokumenter/mastering-emacs-v4.pdf"
        "/mnt/Emacs/.emacs.d/orgmode.el"
        "/home/kim/.dots/.emacs.d/mail.el"
        "/mnt/Emacs/.emacs.d/mail.el"
        "/mnt/Emacs/.emacs.d/init.el"
        "/home/kim/.dots/Em"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
