;;; Automatically generated by ‘recentf’ on Fri Jul 21 06:34:13 2023.

(setq recentf-list
      '(
        "/home/kim/.dots/.emacs.d/init.el"
        "/home/kim/.emacs.d/init.el"
        "/home/kim/.dots/.xinitrc"
        "/home/kim/.xinitrc"
        "/home/kim/.dots/config/awesome/email.lua"
        "/home/kim/.config/awesome/email.lua"
        "/home/kim/.dots/config/awesome/email-widget/count_unread_emails.py"
        "/home/kim/.config/awesome/mail.lua"
        "/home/kim/.dots/config/awesome/rc.lua"
        "/home/kim/.config/awesome/awesome-wm-widgets/battery-widget/battery.lua"
        "/home/kim/.config/awesome/awesome-wm-widgets/volume-widget/README.md"
        "/home/kim/.config/awesome/rc.lua"
        "/home/kim/.config/awesome/themes/default/theme.lua"
        "/home/kim/.dots/config/alacritty/alacritty.yml"
        "/home/kim/.config/alacritty/alacritty.yml"
        "/home/kim/.dots/.emacs.d/orgmode.el"
        "/home/kim/Dokumenter/mastering-emacs-v4.pdf"
        "/home/kim/.dots/.emacs.d/mail.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
