;; -*- emacs-lisp -*- <23/01/01 11:05:55 /home/kim/.config/emacs/var/tramp/persistency.el>
;; Tramp connection history.  Don't change this file.
;; Run `M-x tramp-cleanup-all-connections' instead.

(((tramp-file-name "sudo" "root" nil "Arch" nil nil nil)
  ("null-device" "/dev/null")
  ("uname" "Linux 6.1.1-arch1-1")
  ("locale" "LC_ALL=C.UTF-8")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"))
  ("pipe-buf" 4096)
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("case-insensitive" nil)
  ("stat" "env QUOTING_STYLE=locale \\stat")
  ("bzr" nil)
  ("git" "\\git")
  ("hg" nil)
  ("id" "/bin/id")
  ("gid-string" "root")
  ("uid-string" "root")
  ("readlink" "\\readlink")
  ("gid-integer" 0)
  ("uid-integer" 0)
  ("~root" "/root")
  ("ln" "\\ln")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")))
