#!/bin/sh

n=$(cat /sys/class/power_supply/BAT0/capacity)
m=$(cat /sys/class/power_supply/BAT1/capacity)

sum=$(($n+$m))
ans=$(($sum / 2))

if [ "$ans" -gt 97 ]; then
   icon="   "
elif [ "$ans" -gt 75 ]; then
    icon="   "
elif [ "$ans" -gt 30 ]; then
    icon="   "
elif [ "$ans" -gt 15 ]; then
    icon="   "
elif [ "$ans" -gt 8 ]; then
    icon="   "
else
    icon="   "
fi



echo "%{B#5e8d87}%{F#1d1f21}${icon}%{F#1d1f21} %{B#8abeb7} BAT ${ans} % "
