#!/bin/bash

PREFIX_PLAY=' '
PREFIX_PAUSE=' '

get_mpd()
{
	current_song="$(mpc current)"

	if [[ "$current_song" = "" ]]; then
		echo ""
		exit 0
	else
		playpause=$(mpc | awk '/\[.*]/{split($0, a, " "); print a[1]}')
		if [[ "$playpause" = "[playing]" ]]; then
			current_song="%{B#295340} %{F#ABC2AB} $PREFIX_PLAY %{B#dd1d1f21} %{F#c5c8c6} $current_song"
		elif [[ "$playpause" = "[paused]" ]]; then
			current_song="%{B#295340} %{F#ABC2AB} $PREFIX_PAUSE %{B#dd1d1f21} %{F#c5c8c6} $current_song"
		fi
	fi

	echo "%{B#295340} %{F#ABC2AB}$current_song"
}

get_mpd

