#!/bin/sh

icon=
n=$(ls /home/kim/.local/share/mail/kim@kimkruse.xyz/INBOX/new | wc -l)
m=$(ls /home/kim/.local/share/mail/mail4kruse@gmail.com/INBOX/new | wc -l)
m=$(ls /home/kim/.local/share/mail/danekikr@gmail.com/INBOX/new | wc -l)
m=$(ls /home/kim/.local/share/mail/kimkruse@hotmail.com/INBOX/new | wc -l)

sum=$(($n+$m))

if [ "$sum" -gt 1 ]; then
  icon="<fc=#c7ae95>   </fc>"
else
  icon="<fc=#81a2be>   </fc>"
fi


echo "${icon}${sum} mails"
